title: Brant (Songfeng) Tan # your name (or website title) here
logo: "/images/profile-large.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MPP, Public Policy Analysis @ Uchicago
  <br>
  Bachelor @ Sun Yat-sen University
  <br><br>
  My name's Brant. I'm striving to be a xxx that integrates modern-day technology into traditional problem solving. As you can see on the right are collections of group or individual projects for class or work. I have experience in data analysis with Python and R, in ArcGIS, and in infomational platforms such as Capital IQ.
  <br><br>
  Note: Some lines might be shadowed to conform confidentiality
  <br><br>
  <a href="www.linkedin.com\in\brant-songfeng-tan\">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
