title: Brant (Songfeng) Tan # your name (or website title) here
logo: "/images/profile-large.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MPP, Public Policy Analysis @ Uchicago, IL USA
  <br><br>
  Bachelor of Laws, International Relations and Economics @ Sun Yat-sen University, CHN
  <br><br>
  Welcome to my professional showcase page! My name's Brant. I've had experiences in several strategy-related internships. I'm interested in working in consulting and strategy-related position. I'm good at researching information, analyzing problems and presenting solutions, as you can see on the right. Open to talk about my work anytime so feel free to reach out!
  <br><br>
  <a href="www.linkedin.com\in\brant-songfeng-tan\">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
